### ISSUE TITLE
Replace occurrences of DEPLOY_UNIT with TEAM

### ISSUE THREAD

**Issue by aablsk** [aablsk/bank-of-anthos#15]
### Describe request or inquiry 
Replace mentions of deploy unit/DEPLOY_UNIT with team/TEAM

### What purpose/environment will this feature serve? 
Since we have agreed to use "teams" in our language instead of "deploy units" we should adapt the corresponding resources to reflect this.

**Comment by palladius** [comment]
Fixed with commit 422bef4da3b0e6049812f066d07eee1d14ea9c85

**Comment by palladius** [comment]
issues/15 fixed: Replace occurrences of DEPLOY_UNIT with TEAM
    

1.      changed all Occurrences of _DEPLOY_UNIT with _TEAM
2.      Changed all occurrences of DEPLOY_UNIT with TEAM (after 1)
3.      Changed all occurrences of 'deploy unit' with 'team'

    
    Added some minor quoting in a description which of course could blow EVERYTHING up in clouddeploy.yaml :)
